# datasource
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#rocketmq, 自定义属性
rocketmq.name.server.address=
#redis
spring.redis.host=
spring.redis.port=
spring.redis.password=
#fastdfs
#是一个tracher列表，可为多个，用逗号分隔开
fdfs.tracker-list=
fdfs.http.storage-addr=
#file
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=1GB
#elasticsearch
elasticsearch.url=192.168.248.139:9200